apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: registry.cn-shenzhen.aliyuncs.com/kubeops/ad-das-platform-client:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.3"
              memory: "300Mi"
            requests:
              cpu: "0.3"
              memory: "300Mi"
