apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  selector:
    matchLabels:
      app: master
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: registry.cn-shenzhen.aliyuncs.com/kubeops/ad-das-platform-master:latest
          resources:
            limits:
              cpu: "0.3"
              memory: "300Mi"
            requests:
              cpu: "0.3"
              memory: "300Mi"
